# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 18:53
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Championship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_championship', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название чемпионата')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Название клуба')),
                ('main_coach', models.CharField(blank=True, max_length=50, null=True, verbose_name='Главный тренер')),
                ('logo', models.ImageField(upload_to='...', verbose_name='Логотип клуба')),
                ('based', models.DateField(blank=True, null=True, verbose_name='Дата основания')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Цвет')),
                ('achievement', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=50, null=True, verbose_name='Достижения')),
                ('stadium', models.CharField(blank=True, max_length=50, null=True, verbose_name='Стадион')),
                ('championships', models.ManyToManyField(to='tournaments.Championship')),
            ],
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour', models.IntegerField(blank=True, verbose_name='Тур')),
                ('match_date', models.DateField(blank=True, null=True, verbose_name='День матча')),
                ('goals_guest', models.IntegerField(default=0, verbose_name='Забито гостями')),
                ('goals_home', models.IntegerField(default=0, verbose_name='Забито дома')),
                ('guest_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_club', to='tournaments.Club')),
                ('home_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_club', to='tournaments.Club')),
                ('сhampionship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.Championship')),
            ],
        ),
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_time', models.DateTimeField()),
                ('event_match', models.CharField(choices=[('penalty', 'Пенальти'), ('assists', 'Ассист'), ('yellow_card', 'Жёлтая карточка'), ('red_card', 'Красная карточка'), ('Goal', 'Гол')], max_length=50)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.Matches')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Имя игрока')),
                ('position', models.CharField(choices=[('goalkeeper', 'Вратарь'), ('defender', 'Защитник'), ('halfback', 'Полузашитник'), ('forward', 'Нападающий')], max_length=10, verbose_name='Позиция')),
                ('number', models.IntegerField(blank=True, verbose_name='Номер игрока')),
                ('citizenship', models.CharField(blank=True, max_length=20, null=True, verbose_name='Гражданство')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('foto', models.ImageField(upload_to='players_images/', verbose_name='Фото игрока')),
            ],
        ),
        migrations.AddField(
            model_name='matchevent',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.Player'),
        ),
        migrations.AddField(
            model_name='club',
            name='players',
            field=models.ManyToManyField(to='tournaments.Player'),
        ),
    ]
