# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='guest_club',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest_club', to='tournaments.Club'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='home_club',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_club', to='tournaments.Club'),
        ),
    ]
