# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 11:34
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_auto_20170425_2237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='championship',
            options={'verbose_name': 'чемпионат', 'verbose_name_plural': 'чемпионаты'},
        ),
        migrations.AlterModelOptions(
            name='club',
            options={'verbose_name': 'клуб', 'verbose_name_plural': 'клубы'},
        ),
        migrations.AlterModelOptions(
            name='matches',
            options={'verbose_name': 'матч', 'verbose_name_plural': 'матчи'},
        ),
        migrations.AlterModelOptions(
            name='matchevent',
            options={'verbose_name': 'событие матча', 'verbose_name_plural': 'события матча'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'игрок', 'verbose_name_plural': 'игроки'},
        ),
        migrations.AlterField(
            model_name='championship',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='club',
            name='achievement',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Достижения'),
        ),
        migrations.AlterField(
            model_name='club',
            name='championships',
            field=models.ManyToManyField(related_name='clubs', to='tournaments.Championship'),
        ),
        migrations.AlterField(
            model_name='club',
            name='players',
            field=models.ManyToManyField(related_name='clubs', to='tournaments.Player'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='goals_guest',
            field=models.IntegerField(blank=True, null=True, verbose_name='Забито гостями'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='goals_home',
            field=models.IntegerField(blank=True, null=True, verbose_name='Забито дома'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='match_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='День матча'),
        ),
        migrations.AlterField(
            model_name='matchevent',
            name='event_match',
            field=models.CharField(choices=[('penalty', 'Пенальти'), ('assists', 'Ассист'), ('yellow_card', 'Жёлтая карточка'), ('red_card', 'Красная карточка'), ('goal', 'Гол')], max_length=50, verbose_name='Собитие'),
        ),
        migrations.AlterField(
            model_name='matchevent',
            name='event_time',
            field=models.DateTimeField(verbose_name='Время события'),
        ),
        migrations.AlterField(
            model_name='matchevent',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tournaments.Matches', verbose_name='матч'),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('goalkeeper', 'Вратарь'), ('defender', 'Защитник'), ('halfback', 'Полузащитник'), ('forward', 'Нападающий')], max_length=10, verbose_name='Позиция'),
        ),
    ]
