# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 12:04
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_auto_20170427_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='PenaltyClub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField(verbose_name='Очки')),
                ('reason', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Причина')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.Club', verbose_name='Клуб')),
            ],
            options={
                'verbose_name': 'наказание',
                'verbose_name_plural': 'наказания',
            },
        ),
    ]
