# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 06:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_penaltyclub'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='guest_players',
            field=models.ManyToManyField(blank=True, related_name='guest_players', to='tournaments.Player', verbose_name='Состав гостевой команды'),
        ),
        migrations.AddField(
            model_name='matches',
            name='home_players',
            field=models.ManyToManyField(blank=True, related_name='home_players', to='tournaments.Player', verbose_name='Состав домашней команды'),
        ),
        migrations.AlterField(
            model_name='club',
            name='championships',
            field=models.ManyToManyField(related_name='clubs', to='tournaments.Championship', verbose_name='Чемпионат'),
        ),
        migrations.AlterField(
            model_name='club',
            name='players',
            field=models.ManyToManyField(related_name='players', to='tournaments.Player', verbose_name='Игроки'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='guest_club',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest_club', to='tournaments.Club', verbose_name='Гостевой клуб'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='home_club',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_club', to='tournaments.Club', verbose_name='Домашний клуб'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='сhampionship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='сhampionship', to='tournaments.Championship', verbose_name='Чемпионат'),
        ),
        migrations.AlterField(
            model_name='matchevent',
            name='event_match',
            field=models.CharField(choices=[('penalty', 'Пенальти'), ('yellow_card', 'Жёлтая карточка'), ('red_card', 'Красная карточка'), ('goal', 'Гол')], max_length=50, verbose_name='Собитие'),
        ),
        migrations.AlterField(
            model_name='matchevent',
            name='event_time',
            field=models.CharField(max_length=50, verbose_name='Время события'),
        ),
        migrations.AlterField(
            model_name='matchevent',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.Player', verbose_name='Игрок'),
        ),
        migrations.AlterField(
            model_name='penaltyclub',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='tournaments.Club', verbose_name='Клуб'),
        ),
    ]
