# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_auto_20170510_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='players',
            field=models.ManyToManyField(related_name='clubs', to='tournaments.Player', verbose_name='Игроки'),
        ),
        migrations.AlterField(
            model_name='matchevent',
            name='event_match',
            field=models.CharField(choices=[('replacement', 'Замена'), ('yellow_card', 'Жёлтая карточка'), ('red_card', 'Красная карточка'), ('goal', 'Гол')], max_length=50, verbose_name='Собитие'),
        ),
    ]
