# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_auto_20170527_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchevent',
            name='event_match',
            field=models.CharField(choices=[('replacement', 'Замена'), ('yellow_card', 'Жёлтая карточка'), ('red_card', 'Красная карточка'), ('goal', 'Гол'), ('autogoal', 'автогол')], max_length=50, verbose_name='Собитие'),
        ),
    ]
