# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 06:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20170413_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 13, 6, 12, 23, 605994, tzinfo=utc)),
        ),
    ]
