# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
        ('registration', '0006_auto_20170413_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favorite_team',
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_players',
            field=models.ManyToManyField(blank=True, null=True, to='tournaments.Player'),
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_teams',
            field=models.ManyToManyField(blank=True, null=True, to='tournaments.Club'),
        ),
    ]
