# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20170420_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorite_players',
            field=models.ManyToManyField(blank=True, to='tournaments.Player'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favorite_teams',
            field=models.ManyToManyField(blank=True, to='tournaments.Club'),
        ),
    ]
