# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 06:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_auto_20170425_2237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'профиль', 'verbose_name_plural': 'профили'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='activation_key',
            field=models.CharField(blank=True, max_length=40, verbose_name='Ключ активации'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favorite_players',
            field=models.ManyToManyField(blank=True, related_name='favorite_players', to='tournaments.Player', verbose_name='Любимый игрок'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favorite_teams',
            field=models.ManyToManyField(blank=True, related_name='clubs', to='tournaments.Club', verbose_name='Любимая команда'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='key_expires',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время деактивации'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=30, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
